### ISSUE TITLE
-r option doesnt work (resolve ip option)

### ISSUE THREAD

**Issue by dannatofrenk** [ropnop/windapsearch#23]
May be is something in my configuration but looks like a type of data error

str instance, bytes found....

Traceback (most recent call last):
  File "windapsearch/./windapsearch.py", line 825, in <module>
    run(args)
  File "windapsearch/./windapsearch.py", line 610, in run
    allComputersDict = ldapSession.getComputerDict(allComputers, ipLookup=True)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "windapsearch/./windapsearch.py", line 380, in getComputerDict
    computerInfo[attr] = ','.join(computer.get_attr_values(attr))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 0: expected str instance, bytes found

**Comment by phil0u** [comment]
Dirty patch, but it makes it work for me : 

diff -Naur ../../windapsearch-git/windapsearch.py ./windapsearch.py 
--- ../../windapsearch-git/windapsearch.py      2024-01-20 12:23:55.651569405 +0100
+++ ./windapsearch.py   2024-01-20 17:25:24.675969137 +0100
@@ -377,7 +377,7 @@
             computerInfo = {}
             dn = computer.dn
             for attr in computer.get_attr_names():
-                computerInfo[attr] = ','.join(computer.get_attr_values(attr))
+                computerInfo[attr] = str(b','.join(computer.get_attr_values(attr)))
 
             if 'dNSHostName' in computerInfo:
                 hostname = computerInfo['dNSHostName']
@@ -487,7 +487,7 @@
                     'operatingSystemServicePack']
     attrs = []
 
-    for dn, computer in results.iteritems():
+    for dn, computer in results.items():
         for key in computer:
             keys.add(key)

**Comment by phil0u** [comment]
Dirty patch attached, makes it work for me
[windapsearch.py.patch](https://github.com/ropnop/windapsearch/files/13998592/windapsearch.py.patch)
